[package]
name = "koharu"
version.workspace = true
edition.workspace = true
description.workspace = true
authors.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
publish.workspace = true
license.workspace = true
include = [
    "src/**",
    "icons/**",
    "README.md",
]

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
git-version = { workspace = true }
koharu-app = { workspace = true }
rfd = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
console = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
image = { workspace = true }
koharu-config = { workspace = true }
koharu-pipeline = { workspace = true }
koharu-scene = { workspace = true }
koharu-translator = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true }
windows-sys = { workspace = true }
winreg = { workspace = true }
