/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { DataConfig } from './dataConfig'
import type { HttpConfig } from './httpConfig'
import type { PipelineConfig } from './pipelineConfig'
import type { ProviderConfig } from './providerConfig'

export interface AppConfig {
  data?: DataConfig
  http?: HttpConfig
  pipeline?: PipelineConfig
  providers?: ProviderConfig[]
}
