/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { DownloadProgress } from './downloadProgress'
import type { JobFinishedEvent } from './jobFinishedEvent'
import type { JobWarningEvent } from './jobWarningEvent'
import type { LlmTarget } from './llmTarget'
import type { PipelineProgress } from './pipelineProgress'
import type { SnapshotEvent } from './snapshotEvent'

export type AppEvent =
  | {
      event: 'jobStarted'
      id: string
      kind: string
    }
  | (PipelineProgress & {
      event: 'jobProgress'
    })
  | (JobWarningEvent & {
      event: 'jobWarning'
    })
  | (JobFinishedEvent & {
      event: 'jobFinished'
    })
  | (DownloadProgress & {
      event: 'downloadProgress'
    })
  | {
      event: 'llmLoading'
      target: LlmTarget
    }
  | {
      event: 'llmLoaded'
      target: LlmTarget
    }
  | {
      event: 'llmFailed'
      target?: null | LlmTarget
    }
  | {
      event: 'llmUnloaded'
    }
  | (SnapshotEvent & {
      event: 'snapshot'
    })
