/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { DataConfigPatch } from './dataConfigPatch'
import type { HttpConfigPatch } from './httpConfigPatch'
import type { PipelineConfigPatch } from './pipelineConfigPatch'
import type { ProviderPatch } from './providerPatch'

/**
 * Sparse patch for `koharu_app::AppConfig`. Missing fields mean "leave
 * as-is". The `providers` field, if present, replaces the whole provider
 * list — we do not merge by id because ordering is meaningful.
 */
export interface ConfigPatch {
  data?: null | DataConfigPatch
  http?: null | HttpConfigPatch
  pipeline?: null | PipelineConfigPatch
  /**
   * If present, replaces the entire list. Api_key values of `"[REDACTED]"`
   * are interpreted as "leave the existing secret alone".
   * @nullable
   */
  providers?: ProviderPatch[] | null
}
