/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export type ExportFormat = (typeof ExportFormat)[keyof typeof ExportFormat]

export const ExportFormat = {
  khr: 'khr',
  psd: 'psd',
  rendered: 'rendered',
  inpainted: 'inpainted',
} as const
