/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { ExportFormat } from './exportFormat'
import type { PageId } from './pageId'

export interface ExportProjectRequest {
  /**
   * Optional global font override (from UI preferences).
   * @nullable
   */
  defaultFont?: string | null
  format: ExportFormat
  /**
   * Optional subset of pages; defaults to every page.
   * @nullable
   */
  pages?: PageId[] | null
}
