/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export type FontSource = (typeof FontSource)[keyof typeof FontSource]

export const FontSource = {
  system: 'system',
  google: 'google',
} as const
