/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { FontSource } from './fontSource'

export interface FontFaceInfo {
  cached: boolean
  /** @nullable */
  category?: string | null
  familyName: string
  postScriptName: string
  source: FontSource
}
