/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface HistoryResult {
  /**
   * New epoch. `None` only for a no-op undo/redo at the stack boundary.
   * @minimum 0
   * @nullable
   */
  epoch?: number | null
}
