/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface HuggingFaceConfigPatch {
  /**
   * `"[REDACTED]"` → keep existing keyring secret; empty → clear; otherwise save.
   * @nullable
   */
  token?: string | null
}
