/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

/**
 * HuggingFace access, for the gated model repositories.
 */
export interface HuggingFaceConfig {
  /**
   * Populated from credential storage on `load()`, never written to
   * config.toml. Serializes as `"[REDACTED]"` in API responses.
   *
   * Only some model repositories need this. `deepghs/AnimeText_yolo` is
   * `gated: auto`: the terms have to be accepted on the repo page and the
   * request has to be authenticated. When unset, koharu still honors
   * `HF_TOKEN` and the `hf auth login` file.
   * @nullable
   */
  token?: string | null
}
