/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { BlobRef } from './blobRef'

export interface ImageDataPatch {
  blob?: null | BlobRef
  /** @nullable */
  name?: string | null
  /**
   * @minimum 0
   * @nullable
   */
  naturalHeight?: number | null
  /**
   * @minimum 0
   * @nullable
   */
  naturalWidth?: number | null
  /** @nullable */
  opacity?: number | null
}
