/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

/**
 * A non-fatal step failure during a pipeline run. The pipeline recovers by
 * skipping the rest of the current page's steps and moving on to the next
 * page; the UI accumulates these into a list during the job.
 */
export interface JobWarningEvent {
  jobId: string
  message: string
  /**
   * 0-based page index where the failure happened.
   * @minimum 0
   */
  pageIndex: number
  /** Engine id (e.g. `"lama-manga"`) of the step that failed. */
  stepId: string
  /** @minimum 0 */
  totalPages: number
}
