/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { DownloadProgress } from './downloadProgress'

export interface ListDownloadsResponse {
  downloads: DownloadProgress[]
}
