/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { LlmCatalogModel } from './llmCatalogModel'
import type { LlmProviderCatalog } from './llmProviderCatalog'

export interface LlmCatalog {
  localModels: LlmCatalogModel[]
  providers: LlmProviderCatalog[]
}
