/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface LlmGenerationOptions {
  /** @nullable */
  customSystemPrompt?: string | null
  /**
   * @minimum 0
   * @nullable
   */
  maxTokens?: number | null
  /** @nullable */
  temperature?: number | null
}
