/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { LlmGenerationOptions } from './llmGenerationOptions'
import type { LlmTarget } from './llmTarget'

export interface LlmLoadRequest {
  options?: null | LlmGenerationOptions
  target: LlmTarget
}
