/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { LlmStateStatus } from './llmStateStatus'
import type { LlmTarget } from './llmTarget'

export interface LlmState {
  /** @nullable */
  error?: string | null
  status: LlmStateStatus
  target?: null | LlmTarget
}
