/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export type LlmTargetKind = (typeof LlmTargetKind)[keyof typeof LlmTargetKind]

export const LlmTargetKind = {
  local: 'local',
  provider: 'provider',
} as const
