/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface NamedFontPrediction {
  /** @minimum 0 */
  index: number
  /** @nullable */
  language?: string | null
  name: string
  probability: number
  serif: boolean
}
