/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { ImageData } from './imageData'
import type { MaskData } from './maskData'
import type { TextData } from './textData'

export type NodeKind =
  | {
      image: ImageData
    }
  | {
      text: TextData
    }
  | {
      mask: MaskData
    }
