/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { NodeDataPatch } from './nodeDataPatch'
import type { Transform } from './transform'

export interface NodePatch {
  data?: null | NodeDataPatch
  transform?: null | Transform
  /** @nullable */
  visible?: boolean | null
}
