/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { NodeId } from './nodeId'
import type { NodeKind } from './nodeKind'
import type { Transform } from './transform'

export interface Node {
  id: NodeId
  kind: NodeKind
  transform?: Transform
  visible: boolean
}
