/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { Node } from './node'

/**
 * Stacking = insertion order. Bottom-first: `source` is typically first,
 * `rendered` typically last.
 */
export type PageNodes = { [key: string]: Node }
