/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface PagePatch {
  /**
   * @minimum 0
   * @nullable
   */
  height?: number | null
  /** @nullable */
  name?: string | null
  /**
   * @minimum 0
   * @nullable
   */
  width?: number | null
}
