/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export type PipelineStatus =
  | {
      status: 'running'
    }
  | {
      status: 'completed'
    }
  | {
      status: 'cancelled'
    }
  | {
      reason: string
      status: 'failed'
    }
