/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { ProjectStyle } from './projectStyle'

export interface ProjectMeta {
  createdAt: string
  name: string
  style?: ProjectStyle
  updatedAt: string
}
