/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { ProjectStyle } from './projectStyle'

export interface ProjectMetaPatch {
  /** @nullable */
  name?: string | null
  style?: null | ProjectStyle
  /** @nullable */
  updatedAt?: string | null
}
