/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface ProviderPatch {
  /**
   * `"[REDACTED]"` → keep existing keyring secret; empty → clear; otherwise save.
   * @nullable
   */
  apiKey?: string | null
  /** @nullable */
  baseUrl?: string | null
  id: string
}
