/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export type PutMaskParams = {
  /**
   * Optional pipeline engine to run after the mask is updated.
   * @nullable
   */
  pipeline?: string | null
  /**
   * Bounding box for the pipeline run.
   * @nullable
   */
  x?: number | null
  /**
   * @nullable
   */
  y?: number | null
  /**
   * @nullable
   */
  width?: number | null
  /**
   * @nullable
   */
  height?: number | null
}
