/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export type ReadingOrder = (typeof ReadingOrder)[keyof typeof ReadingOrder]

export const ReadingOrder = {
  rtl: 'rtl',
  ltr: 'ltr',
  custom: 'custom',
} as const
