/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface Region {
  /** @minimum 0 */
  height: number
  /** @minimum 0 */
  width: number
  /** @minimum 0 */
  x: number
  /** @minimum 0 */
  y: number
}
