/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { Page } from './page'

/**
 * Pages in insertion order; `IndexMap` ordering *is* the page order.
 */
export type ScenePages = { [key: string]: Page }
