/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { Scene } from './scene'

/**
 * JSON-shaped scene snapshot for the UI (no postcard decoder in JS).
 */
export interface SceneSnapshot {
  /** @minimum 0 */
  epoch: number
  scene: Scene
}
