/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface StartDownloadRequest {
  /**
   * Package id, as declared via `declare_hf_model_package!`
   * (e.g. `"model:comic-text-detector:onnx"`).
   */
  modelId: string
}
