/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { TextAlign } from './textAlign'
import type { TextShaderEffect } from './textShaderEffect'
import type { TextStrokeStyle } from './textStrokeStyle'

export interface TextStyle {
  /** @items.minimum 0 */
  color: number[]
  effect?: null | TextShaderEffect
  fontFamilies: string[]
  /** @nullable */
  fontSize?: number | null
  stroke?: null | TextStrokeStyle
  textAlign?: null | TextAlign
}
