/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface TextStrokeStyle {
  /** @items.minimum 0 */
  color?: number[]
  enabled?: boolean
  /** @nullable */
  widthPx?: number | null
}
