/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export type TextAlign = (typeof TextAlign)[keyof typeof TextAlign]

export const TextAlign = {
  left: 'left',
  center: 'center',
  right: 'right',
} as const
